Mobile first responsive design
sumon766/portfolio-mobile-first pull request #1
Opened 2023-01-13 09:34 UTC by sumon766

Add responsiveness
Add a mobile menu button
Add introduction content

2023-01-13 11:50 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: :

Hi @sumon766 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif">

## Highlights :tophat:  :+1: 

- No linter errors :+1: 
- Good README :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 11:50 UTC, GedeonTS commented on index.html
> +                    </div>
- [ ] Kindly make sure all the images or forms are added as background-image and they do fit inside the section to meet the project requirements. :recycle: 
![Yimage](https://user-images.githubusercontent.com/97834160/212309538-7acde636-6b7b-4212-aa9e-230a592d2c6a.png)

2023-01-13 11:50 UTC, GedeonTS commented on index.html
> +                        <p>
- [ ] :thinking:  In my opinion, it would be better to use h3 only if we already have h2, I suggest using h2 here instead. :recycle:

2023-01-13 11:50 UTC, GedeonTS commented on index.html
> +        <main>
- [ ] As per the project requirements, :thinking: kindly make this a section instead of main, for semantic purpose :recycle:

2023-01-13 11:50 UTC, GedeonTS commented on index.html
> +                        </ul> -->
- [ ] Kindly make sure to remove all commented-out lines of code to make your code clean :recycle:

2023-01-13 11:50 UTC, GedeonTS commented on index.html
> +                        <a class="navbar-brand" href="#">John Doe</a>
- [ ] Good job going beyond the requirements for this milestone :+1: , kindly make sure the header is a flexbox and take into account the structure below to meet the semanitc HTML rules. :point_down: 

`<header>`
`<p>My logo</p>`
`<nav>`
`<ul>`
`<li><a href="">Portfolio</a></li>`
`<li><a href="">About</a></li>`
....
`<ul>`
`<img sr="humbuger.png">`
`</nav>`
`<header>`

2023-01-13 11:50 UTC, GedeonTS commented on style.css
> +  background-color: #1c1a19;
- [ ] :thinking: As per the project requirements, kindly make sure the headline section is a flexbox :recycle:

2023-01-13 11:50 UTC, GedeonTS commented on style.css
> +  padding: 0;
- [ Kindly make sure the social icon area meets the colors, margins, and paddings of the Figma design as we have to stick to it as much as possible :recycle: 

YOUR DESIGN:
![Yicons](https://user-images.githubusercontent.com/97834160/212313689-ed5d36d7-2034-4d7d-9511-9c8e06e1d855.png)


FIGMA:
![Fic](https://user-images.githubusercontent.com/97834160/212313712-bc82dfc7-de51-496c-92a1-ad1b43aa9486.png)

2023-01-14 07:04 UTC, sumon766 commented on index.html
> +                    </div>
@GedeonTS It's not important to add all images as background images. I can also insert images using HTML. I guess there should be no issue with anything.

2023-01-14 07:07 UTC, sumon766 commented on index.html
> +                        <a class="navbar-brand" href="#">John Doe</a>
@GedeonTS I am using bootstrap for responsiveness purposes, why do I have to use flexbox on my webpage? According to the requirement, I have been suggested to use flexbox, but it's not mandatory I believe. Also, I am yet learning flexbox, I haven't yet become sure how to integrate flexbox with this design. So I hope that bootstrap is serving my purposes and I am permitted to use this and skip using flexbox.

2023-01-14 07:12 UTC, sumon766 commented on style.css
> +  background-color: #1c1a19;
@GedeonTS Thank you again for the suggestion, I can understand that flexbox is an awesome property and can be used for better flexibility. But in my case, I am using bootstrap and it does not require flexbox to be used with this. Using flexbox can break my design and may not serve my purpose. Also, to use flexbox I have to raw code the complete responsiveness and I am yet to learn CSS, so I hope that there should be no issue using bootstrap.

2023-01-14 09:41 UTC, AbayomiOlaoye requested changes
Hi @sumon766 👍 👍 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so_close](https://user-images.githubusercontent.com/99715640/211872359-9a4d36f7-0386-4000-82a4-c274b06a5ce4.gif)


 ## Highlights 🎯 
- Good PR message ✅ 
- Great commit messages ✅ 
- No linter error ✅ 
- Correct GitHub flow ✅ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 09:41 UTC, AbayomiOlaoye commented on index.html
> +                    </div>
👏 Good point, @sumon766 👍 
- It's quite understandable what you are trying to point out here but images that are not considered as part of the main content of a page are added using `css's` `background-image` properties. This is best practice and it's good for aesthetics.
_For more clarification please read [this article](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image) on when to use `img` or `background-image`_ .
- [ ] Kindly implement the previous reviewer's suggestion as it is part of the requirement
- [ ] Also, please consider using the appropriate image for mobile screen for aesthetic reasons. It will make your design more decent and impressive.
_Like this:_
![image](https://user-images.githubusercontent.com/99715640/212465075-1713c4ab-6ca9-45e2-886c-12b589b44663.png)

2023-01-14 09:41 UTC, AbayomiOlaoye commented on index.html
> +
- [ ] [OPTIONAL] How about removing extra lines from your code? This is good practice and it makes your more more readable, understandable and reduce the chance mistakenly filling spaces up with unwanted bugs

2023-01-14 09:41 UTC, AbayomiOlaoye commented on index.html
> +            </div>
- [ ] [OPTIONAL] I see that you are eager to proceed with the next project 😆 and that's great but leaving empty empty elements is the same with having extra lines or retaining commented codes in your workspace. This is not considered a good practice. I suggest you remove these empty set of codes.

2023-01-14 09:41 UTC, AbayomiOlaoye commented on index.html
> +                                </li>
- [ ] [OPTIONAL] If you are like me 😉 , I would like people to be able to contact me for opportunities, or connect with me from my portfolio. If that sounds good, consider setting your `href` attribute to your social media profile links/usernames

2023-01-14 09:41 UTC, AbayomiOlaoye commented on style.css
> +  color: #fff !important;
- [ ] [OPTIONAL] On the use of professional, I suggest you limit it to at most 2 in all your documents. It has a way of potentially introducing bugs in your code, and some specificity issues. Please read this [HTML/CSS best practice](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md), especially the 9th item on the list.

2023-01-14 09:41 UTC, AbayomiOlaoye commented on style.css
> +  background-color: #1c1a19;
- [ ] This is a brilliant idea that shows your strength, and this is good 👏. However, according to the expectation of the [requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md), I'll suggest that you try to implement the suggestion from your previous code reviewer. I have include a link to the requirement it says `"should use flexbox"` or you can check the screenshot below:

![image](https://user-images.githubusercontent.com/99715640/212465462-f377e976-aba3-4e4f-aa58-73fb1dee9dc3.png)

- Kindly note that the purpose of this project is to test your knowledge according the lessons you learnt during the week and to sharpen your ability to solve problems. Bootstrap is good but it not required here. Please go through the lesson on `flexbox` and I am sure you'd love it when you grasp it. 💪 You can thank me later 😉

2023-01-14 09:41 UTC, AbayomiOlaoye commented on style.css
> +  padding: 0;
- Nice job there! 👍 
- [ ] You are almost done with this! The social icons are still too small and slightly different from the figma design, and this is not too good for user experience and users with sight issues (accessibility issues). Kindly check the outcomes from both end and see how to make corrections - this might be to download the icons from `Figma` directly:
- Here is your design:
![image](https://user-images.githubusercontent.com/99715640/212465698-9a175c38-0e77-4dec-9ce6-21d884f20536.png)

- Here is figma design:
![image](https://user-images.githubusercontent.com/99715640/212465739-57912909-b505-4aca-bfa6-62015dcb837e.png)

2023-01-14 14:18 UTC, Zuhaib042 requested changes
Hi @sumon766 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![close](https://media.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif)

 ## Highlights
Good PR message ✅
Great commit messages ✅
No linter error ✅
Correct GitHub flow ✅

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 14:18 UTC, Zuhaib042 commented on index.html
> +                </div>
- [ ] I think your design has some issues that needs to be fixed to get to the next project. As previous code reviewer mentioned, the background-image needs to be on its place as it is in the Figma design. our design needs to be identical to the figma design.kindly consider fixing that.
your design
![asdf](https://user-images.githubusercontent.com/96683843/212475704-078ae3f1-6bc8-4cd4-adcd-1e7a47d06df9.jpg)

figma design
![as](https://user-images.githubusercontent.com/96683843/212475667-c9b24ac3-ea9e-4983-9c2e-0e574b305180.jpg)

2023-01-14 14:18 UTC, Zuhaib042 commented on index.html
> +                </div>
- [ ] Previously, these `a` tags were wrapped with `li` and those `li`s were children of `ul`. this is a project requirement and I would suggest implementing that. 
- [OPTIONAL] what the previous reviewer meant was to give appropriate links in `href=""` attribute of `a` tags.

2023-01-14 14:18 UTC, Zuhaib042 commented on style.css
> +}
- [OPTIONAL] Instead of this, just writing these lines would do the trick and its best for DRY principle.
```
* {
margin: 0;
padding: 0;
}
```

2023-01-14 14:18 UTC, Zuhaib042 commented on style.css
> +  }
- [OPTIONAL] On the use of professional, I suggest you limit it to at most 2 in all your documents. It has a way of potentially introducing bugs in your code, and some specificity issues. Please read this [HTML/CSS best practice](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md), especially the 9th item on the list.

2023-01-14 14:18 UTC, Zuhaib042 commented on style.css
> +    right: 0;
[OPTIONAL] On the use of professional, I suggest you limit it to at most 2 in all your documents. It has a way of potentially introducing bugs in your code, and some specificity issues. Please read this [HTML/CSS best practice](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md), especially the 9th item on the list.

2023-01-14 14:18 UTC, Zuhaib042 commented on index.html
> +                        </ul>
- [ ] I think in the figma design and in the requirements, there must be a hamburger menu button here.I would suggest you to fix this and implement menu button like in the figma design instead of navbar links.
your design.
- The hamburger button is on the right, and has a `nav` tag.
- The `nav` tag is for semantics reason, and the right position for convention and user experience for mobile devices.
![qwer](https://user-images.githubusercontent.com/96683843/212476462-e68041af-bab6-4476-b5a8-b40ad06523e6.jpg)

figma design
![qw](https://user-images.githubusercontent.com/96683843/212476470-b6eb4f52-7844-4738-93b8-bde2746595b7.jpg)

2023-01-14 14:46 UTC, sumon766 commented on index.html
> +                </div>
@Zuhaib042 Thanks for your review. Please be informed that the design is completely fine in my browser and nowhere it says that the design has to be identical to the figma design. It says, we need to stick as much as possible to the figma design. Also, in my browser, in the mobile view option, as long as I can scroll, the image placement is perfect. So I don't find anything to make changes.

2023-01-14 14:48 UTC, sumon766 commented on index.html
> +                </div>
@Zuhaib042 In this case, it is nowhere mentioned that the links must be created with ul and li tags, but you are saying this is a project requirement. I suggest, please go through the requirement again. Also, there is no requirement of adding links to href="" element, there is no link to add, only adding "#" or without "#" it's fine.

2023-01-14 14:52 UTC, sumon766 commented on style.css
> +    right: 0;
@Zuhaib042 I used this because while using flexbox, the media queries are not working until I add "!important", I am still in the first week of microverse and learning, not an expert.

2023-01-14 14:55 UTC, sumon766 commented on index.html
> +                        </ul>
![curriculum-html-css-1_setup-md-at-main-·-microverseinc-curriculum-html-css](https://user-images.githubusercontent.com/22003499/212477989-a493ed00-e585-4261-ae2f-f3ea7aa2c282.png)
According to the requirements, I do not have to add the hamburger button, because this will require javascript functionality to work. Also, the design is not necessarily to be identical but stick to it as much as possible. I hope you understand and you can accept the pull request.

2023-01-14 15:57 UTC, sumon766 commented on index.html
> +                </div>
![Portfolio-Mobile-First](https://user-images.githubusercontent.com/22003499/212481327-215e2f77-0e8e-4eb9-ba45-3337804390c0.png)

2023-01-14 18:27 UTC, nicupop729 commented
This PR is under a Second Opinion Review. 
Kindly, don't push other commits and don't ask for another review until a Second Opinion review is provided.

2023-01-14 19:08 UTC, nicupop729 reviewed
Hello @sumon766  👋,

_This is an additional review as a result of the second opinion request._

Kudos for the great effort put in place for this project! :clap:
You are doing great :1st_place_medal: 

Kindly find my inline comments in the review.
When the changes are made, kindly ask for another review from your dashboard.

Keep rocking 🚀!

2023-01-14 19:08 UTC, nicupop729 commented on index.html
> +                </div>
What reviewers mentioned here is that the height of your headline is not fixed, and this makes the background image migrate according to the size of the mobile screen.
The background image looks like in the Figma design for a screen with a screen height of 456px. Rarely you can find this screen size.

Please refactor your background image to replicate the Figma design, as instructed by your previous reviewer.
https://www.loom.com/share/75495f60e86046949a5ce02d52d63f54

2023-01-14 19:08 UTC, nicupop729 commented on style.css
> +}
It will be constructive for you to apply valuable lessons from the reviewers.
Kindly, take it as optional, but highly recommended.

2023-01-14 19:08 UTC, nicupop729 commented on style.css
> +  }
Same here, please take it as optional, but highly recommended. :+1:

2023-01-14 19:08 UTC, nicupop729 commented on style.css
> +    right: 0;
Yes, we know this, and that's why is Optional. 
It will be nice to avoid using `!important;`, but work on this aspect at your own pace.

2023-01-14 19:28 UTC, Zuhaib042 commented on index.html
> +                </div>
Thank you so much @nicupop729 for in-depth clarification

2023-01-16 17:42 UTC, Owusu-Desmond requested changes
Hi @sumon766 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the setup of the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-16 17:42 UTC, Owusu-Desmond commented on index.html
> +                </ul>
- [ ] Please make sure that this section of your project matches the Figma design. From the project requirements, you should stick to the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=Tt1vCN6lfPrkflxz-0), But as you can see there are some differences between the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=Tt1vCN6lfPrkflxz-0) and your design

| Your Design |Figma Design |
| :---:   | :---: | 
| ![Screenshot from 2023-01-16 16-59-24](https://user-images.githubusercontent.com/92303891/212731616-d7b5e60c-5e07-480a-bdae-acd396feb14e.png)| ![Screenshot from 2023-01-16 17-00-28](https://user-images.githubusercontent.com/92303891/212731847-0907e49d-be82-48e1-9efe-e6ce8d78c11e.png) |

2023-01-16 17:42 UTC, Owusu-Desmond commented on index.html
> +                    <h1>John Doe</h1>
- [ ] Please make sure that the logo has a link (a tag). This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info. :pray:

2023-01-16 17:42 UTC, Owusu-Desmond commented on index.html
> +                    <h1>John Doe</h1>
- [ ] Please make sure that the logo has a link (a tag). This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info. :pray:

2023-01-16 17:42 UTC, Owusu-Desmond commented on index.html
> +                            <li><a href="#"><i class="fa fa-envelope"></i></a></li>
- [ ] From the project requirements, you should stick to the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=Tt1vCN6lfPrkflxz-0), But as you can see there are some differences between the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=Tt1vCN6lfPrkflxz-0) and your design
  - It would be better if you make the list of the `Portfolio`, `about`, `blog`, and `contact` invisible on the mobile version.
  - Make sure that the menu icon design looks like the figma design.

| Your Design |Figma Design |
| :---:   | :---: | 
| ![Screenshot from 2023-01-16 17-05-34](https://user-images.githubusercontent.com/92303891/212732693-b1eaf3ce-5aab-4518-ae00-41ee03435ec2.png) | ![Screenshot from 2023-01-16 17-06-20](https://user-images.githubusercontent.com/92303891/212732857-20e5130b-1c95-4001-892a-0e73a3a0ab52.png) |

2023-01-16 17:42 UTC, Owusu-Desmond commented on style.css
> +}
- [ ] From the project requirements, you should stick to the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=Tt1vCN6lfPrkflxz-0), But as you can see there are some differences between the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=Tt1vCN6lfPrkflxz-0) and your design
  - Your background image is not showing as the figma design

| Your Design |Figma Design |
| :---:   | :---: | 
|![Screenshot from 2023-01-16 17-07-49](https://user-images.githubusercontent.com/92303891/212733279-1144e847-26ed-463b-8e59-d059790bd964.png) | ![Screenshot from 2023-01-16 17-10-35](https://user-images.githubusercontent.com/92303891/212738413-81524450-e4e3-4f23-954a-308fd54ebc6c.png)|

2023-01-16 19:10 UTC, bimbolabuari reviewed
Hello @sumon766  👋,

_This is an additional review as a result of the second opinion request._

- Kudos for implementing previously requested changes
  - While most of the requested changes by the last reviewer were right, they should have been optional suggestions in order to be consistent with the last review.
  - I was able to confirm your design, however, I would advise as an optional suggestion( recommended) to work on the design height to take up the entire screen.


https://user-images.githubusercontent.com/66112760/212750767-42e99aac-ba58-46cd-a4c2-51dd0fc945fc.mov



 

  


As this was the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approved right away :)

Keep rocking 🚀!

2023-01-16 19:18 UTC, sumon766 commented
> Hello @sumon766 👋,
> 
> _This is an additional review as a result of the second opinion request._
> 
> * Kudos for implementing previously requested changes
>   
>   * While most of the requested changes by the last reviewer were right, they should have been optional suggestions in order to be consistent with the last review.
>   * I was able to confirm your design, however, I would advise as an optional suggestion( recommended) to work on the design height to take up the entire screen.
> 
>  Screen.Recording.2023-01-16.at.8.08.15.PM.mov 
> As this was the only reason that your project was not approved it will be approved as soon as possible. Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approved right away :)
> 
> Keep rocking 🚀!

2023-01-16 19:22 UTC, sumon766 commented
@bimbolabuari Please tell me how did you confirm my design? Was there any issues with my pushes? One thing I could not be clear also, do you want me to make the mobile 📲 design full screen?

2023-01-17 07:36 UTC, IngDavidTM approved these changes
Hi @sumon766  🙋‍♂️, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 08:07 UTC, merged